version: "3.9"
services:
  db:
    image: "postgres:13.2-alpine"
    environment:
      POSTGRES_DB: plantdiary
      POSTGRES_USER: user
      POSTGRES_PASSWORD: User123
    volumes:
      - postgre_plantdiary_data:/var/lib/postgresql/data
  mail:
    image: "maildev/maildev:1.1.0"
    ports:
      - "1080:80"
  app:
    image: "tfilo/plantdiary:latest"
    ports:
      - "8080:8080"
    environment:
      PD_DATASOURCE: jdbc:postgresql://db:5432/plantdiary
      PD_DATASOURCE_USER: user
      PD_DATASOURCE_PASS: User123
      PD_MAIL_HOST: mail
      PD_MAIL_PORT: 25
    depends_on:
      - db
      - mail
volumes:
  postgre_plantdiary_data: