package sk.filo.plantdiary.enums;

public enum ExceptionCode {
    INVALID_CREDENTIALS,
    DISABLED_USER,
    PLANT_NOT_FOUND,
    EVENT_NOT_FOUND,
    EVENT_TYPE_NOT_FOUND,
    USER_NOT_FOUND,
    LOCATION_NOT_FOUND,
    PHOTO_PROCESSING_FAILED,
    PHOTO_NOT_FOUND,
    PLANT_TYPE_NOT_FOUND;
}
