package sk.filo.plantdiary.enums;

public enum ExceptionCode {
    INVALID_CREDENTIALS,
    DISABLED_USER,
    SESSION_EXPIRED,
    PLANT_NOT_FOUND,
    EVENT_NOT_FOUND,
    EVENT_TYPE_NOT_FOUND,
    USER_NOT_FOUND,
    LOCATION_NOT_FOUND,
    PHOTO_PROCESSING_FAILED,
    PHOTO_NOT_FOUND,
    PLANT_TYPE_NOT_FOUND,
    USERNAME_IN_USE,
    EMAIL_IN_USE,
    SCHEDULE_NOT_FOUND,
    DUPLICATE_SCHEDULE_OF_SAME_TYPE,
    EVENT_TYPE_NOT_SCHEDULABLE;
}
